#+TITLE: el-autoyas.el
#+AUTHOR: Matthew L. Fidler
* Library Information
 /el-autoyas.el/ --- Automatically create Emacs-Lisp Yasnippets

 - Filename :: [[file:el-autoyas.el][el-autoyas.el]]
 - Description :: Automatically create Emacs-Lisp Yasnippets
 - Author :: Matthew L. Fidler
 - Maintainer :: Matthew L. Fidler
 - Created :: Mon Nov 21 10:55:55 2011 (-0600)
 - Version :: 0.5
 - Last-Updated :: Mon Nov 28 08:46:55 2011 (-0600)
 -           By :: Matthew L. Fidler
 -     Update # :: 194
 - URL :: https://github.com/mlf176f2/el-autoyas.el
 - Keywords :: Emacs Lisp Mode Yasnippet
Compatibility: 

* Possible Dependencies

  `assoc', `button', `cl', `easymenu', `eldoc', `help-fns',
  `help-mode', `view', `yasnippet', `yasnippet-bundle'.

* About
el-autoyas is a small complement to yasnippet for emacs-lisp-mode.  It
provides automatically created yasnippets from eldoc argument lists.
* Requirements
 - [[https://github.com/capitaomorte/yasnippet][yasnippet]]
 - eldoc
* Usage
 - To expand the snippet, type the function name or abbrevation and
   then press =TAB=
 - To jump to the next field press =TAB=.  If you did not change the
   field, either the parameter is kept, or replaced with =nil= or
   nothing depending on the argument list.
 - *NOTE* To use some of the more common functions, you may wish to
   delete all the emacs-lisp snippets in the snippets directory.
* Limitations
 - Currently does not support common lisp key functions
 - Unclear if nested snippet expansion is supported.
* Loading el-autoyas in ~/.emacs
You may use marmalade-repo and ELPA to install el-autoyas, or put it
into your load-path and put the following in =~/.emacs=:

#+BEGIN_SRC emacs-lisp
    (require 'el-autoyas)
#+END_SRC
* Functions
** Interactive Functions

** Internal Functions
* Variables
** Customizable Variables

*** el-autoyas-abbrevs
A list of abbreviations that expand to a set function

** Internal Variables

*** el-autoyas-backward-compatability
Yasnippet backward compatability functions used in el-autoyas.el

Value: ((yas/expand-snippet yas-expand-snippet)
 (yas/modified-p yas-modified-p)
 (yas/moving-away-p yas-moving-away-p)
 (yas/text yas-text)
 (yas/skip-and-clear-or-delete-char yas-skip-and-clear-or-delete-char)
 (yas/snippets-at-point yas--snippets-at-point)
 (yas/update-mirrors yas--update-mirrors)
 (yas/fallback-behavior yas-fallback-behavior)
 (yas/minor-mode yas-minor-mode))



*** el-autoyas-load-hook
*Hook run on package load.
Suggestion: Add =el-autoyas-install=.
*Hook run on package load.
Suggestion: Add =el-autoyas-install=.
*Hook run on package load.
Suggestion: Add =el-autoyas-install=.
*Hook run on package load.
Suggestion: Add =el-autoyas-install=.

*** yas-backward-compatability
Yasnippet backward compatability functions used in el-autoyas.el

Value: ((yas/expand-snippet yas-expand-snippet)
 (yas/modified-p yas-modified-p)
 (yas/moving-away-p yas-moving-away-p)
 (yas/text yas-text)
 (yas/skip-and-clear-or-delete-char yas-skip-and-clear-or-delete-char)
 (yas/snippets-at-point yas--snippets-at-point)
 (yas/update-mirrors yas--update-mirrors)
 (yas/fallback-behavior yas-fallback-behavior)
 (yas/minor-mode yas-minor-mode))


*Hook run on package load.
Suggestion: Add =el-autoyas-install=.

*** yas-backward-compatability
Yasnippet backward compatability functions used in el-autoyas.el

Value: ((yas/expand-snippet yas-expand-snippet)
 (yas/modified-p yas-modified-p)
 (yas/moving-away-p yas-moving-away-p)
 (yas/text yas-text)
 (yas/skip-and-clear-or-delete-char yas-skip-and-clear-or-delete-char)
 (yas/snippets-at-point yas--snippets-at-point)
 (yas/update-mirrors yas--update-mirrors)
 (yas/fallback-behavior yas-fallback-behavior)
 (yas/minor-mode yas-minor-mode))


*Hook run on package load.
Suggestion: Add =el-autoyas-install=.

*** yas-backward-compatability
Yasnippet backward compatability functions used in el-autoyas.el

Value: ((yas/expand-snippet yas-expand-snippet)
 (yas/modified-p yas-modified-p)
 (yas/moving-away-p yas-moving-away-p)
 (yas/text yas-text)
 (yas/skip-and-clear-or-delete-char yas-skip-and-clear-or-delete-char)
 (yas/snippets-at-point yas--snippets-at-point)
 (yas/update-mirrors yas--update-mirrors)
 (yas/fallback-behavior yas-fallback-behavior)
 (yas/minor-mode yas-minor-mode))


*Hook run on package load.
Suggestion: Add =el-autoyas-install=.

*** yas-backward-compatability
Yasnippet backward compatability functions used in el-autoyas.el

Value: ((yas/expand-snippet yas-expand-snippet)
 (yas/modified-p yas-modified-p)
 (yas/moving-away-p yas-moving-away-p)
 (yas/text yas-text)
 (yas/skip-and-clear-or-delete-char yas-skip-and-clear-or-delete-char)
 (yas/snippets-at-point yas--snippets-at-point)
 (yas/update-mirrors yas--update-mirrors)
 (yas/fallback-behavior yas-fallback-behavior)
 (yas/minor-mode yas-minor-mode))


*Hook run on package load.
Suggestion: Add =el-autoyas-install=.

*** yas-backward-compatability
Yasnippet backward compatability functions used in el-autoyas.el

Value: ((yas/expand-snippet yas-expand-snippet)
(yas/modified-p yas-modified-p)
(yas/moving-away-p yas-moving-away-p)
(yas/text yas-text)
(yas/skip-and-clear-or-delete-char yas-skip-and-clear-or-delete-char)
(yas/snippets-at-point yas--snippets-at-point)
(yas/update-mirrors yas--update-mirrors)
(yas/fallback-behavior yas-fallback-behavior)
(yas/minor-mode yas-minor-mode))


*Hook run on package load.
Suggestion: Add =el-autoyas-install=.

*** yas-backward-compatability
Yasnippet backward compatability functions used in el-autoyas.el

Value: ((yas/expand-snippet yas-expand-snippet)
(yas/modified-p yas-modified-p)
(yas/moving-away-p yas-moving-away-p)
(yas/text yas-text)
(yas/skip-and-clear-or-delete-char yas-skip-and-clear-or-delete-char)
(yas/snippets-at-point yas--snippets-at-point)
(yas/update-mirrors yas--update-mirrors)
(yas/fallback-behavior yas-fallback-behavior)
(yas/minor-mode yas-minor-mode))


* History

 - 18-Sep-2012 ::  Tested with 0.6. Bug fixes applied. ()
 - 18-Sep-2012 ::  Bug fix for backward compatability ()
 - 12-Sep-2012 ::  Fixed variable yas-backward-compatibility to be el-autoyas-backward-compatability so that things will not collide ()
 - 12-Sep-2012 ::  Another attempt to fix emacswiki documentation ()
 - 12-Sep-2012 ::  Org-readme sync attempt -- trying to fix bug in org-readme. ()
 - 12-Sep-2012 ::  Another attempt to upload el-autoyas without the documentation issues previously observed. ()
 - 12-Sep-2012 ::  Another attempt to sync. ()
 - 12-Sep-2012 ::  Documentation change ()
 - 12-Sep-2012 ::  Updated el-autoyas to support yasnippet 0.8 naming conventions  ()
